import { FolderDataDTO, FolderDTO } from ".";

export const folders: FolderDTO[] = [
    { id: "1", name: "Work Documents", parentId: null },
    { id: "2", name: "Personal Files", parentId: null },
    { id: "3", name: "Projects", parentId: "1" },
    { id: "4", name: "Reports", parentId: "1" },
    { id: "5", name: "Photos", parentId: "2" },
    { id: "6", name: "Vacation", parentId: "5" },
    { id: "7", name: "Invoices", parentId: "3" },
    { id: "8", name: "2024", parentId: "4" },
    { id: "9", name: "2023", parentId: "4" },
    { id: "10", name: "Trip to Paris", parentId: "6" },
];

export const foldersData: FolderDataDTO[] = [
    {
        key: "1",
        name: "Design Materials.zip",
        size: "4.9 MB",
        lastModified: "Jun 23, 2023",
        sharedTo: "5 users",
        isSelected: false,
        folderId: "1",
    },
    {
        key: "2",
        name: "Branding Package.pdf",
        size: "3.7 MB",
        lastModified: "Jun 23, 2023",
        sharedTo: "5 users",
        isSelected: false,
        folderId: "1",
    },
    {
        key: "3",
        name: "Key Visuals.jpg",
        size: "64 KB",
        lastModified: "Jun 23, 2023",
        sharedTo: "5 users",
        isSelected: false,
        folderId: "1",
    },
    {
        key: "4",
        name: "Social Media Template 01.pptx",
        size: "6.2 MB",
        lastModified: "Jun 23, 2023",
        sharedTo: "5 users",
        isSelected: true,
        folderId: "1",
    },
    {
        key: "5",
        name: "Quatation/ Invoice Template Some others wold lorem.xlsx",
        size: "6.2 MB",
        lastModified: "Jun 23, 2023",
        sharedTo: "5 users",
        isSelected: false,
        folderId: "1",
    },
    {
        key: "6",
        name: "Contract Template.docx",
        size: "6.2 MB",
        lastModified: "Jun 23, 2023",
        sharedTo: "5 users",
        isSelected: false,
        folderId: "1",
    },
    {
        key: "7",
        name: "Client Report.xlsx",
        size: "2.3 MB",
        lastModified: "Jun 24, 2023",
        sharedTo: "3 users",
        isSelected: false,
        folderId: "2",
    },
    {
        key: "8",
        name: "Meeting Notes.docx",
        size: "1.1 MB",
        lastModified: "Jun 24, 2023",
        sharedTo: "4 users",
        isSelected: false,
        folderId: "2",
    },
    {
        key: "9",
        name: "Product Overview.pdf",
        size: "5.6 MB",
        lastModified: "Jun 25, 2023",
        sharedTo: "2 users",
        isSelected: true,
        folderId: "2",
    },
    {
        key: "10",
        name: "Marketing Strategy.pptx",
        size: "8.3 MB",
        lastModified: "Jun 25, 2023",
        sharedTo: "6 users",
        isSelected: false,
        folderId: "2",
    },
    {
        key: "11",
        name: "Sales Report.zip",
        size: "3.1 MB",
        lastModified: "Jun 26, 2023",
        sharedTo: "5 users",
        isSelected: false,
        folderId: "3",
    },
    {
        key: "12",
        name: "Employee Handbook.pdf",
        size: "7.2 MB",
        lastModified: "Jun 26, 2023",
        sharedTo: "8 users",
        isSelected: true,
        folderId: "3",
    },
    {
        key: "13",
        name: "Financial Statements.xlsx",
        size: "5.5 MB",
        lastModified: "Jun 27, 2023",
        sharedTo: "4 users",
        isSelected: false,
        folderId: "3",
    },
    {
        key: "14",
        name: "Client Contacts.zip",
        size: "2.4 MB",
        lastModified: "Jun 27, 2023",
        sharedTo: "5 users",
        isSelected: true,
        folderId: "3",
    },
    {
        key: "15",
        name: "Annual Report.pdf",
        size: "10.4 MB",
        lastModified: "Jun 28, 2023",
        sharedTo: "6 users",
        isSelected: false,
        folderId: "4",
    },
    {
        key: "16",
        name: "Company Overview.pptx",
        size: "4.9 MB",
        lastModified: "Jun 28, 2023",
        sharedTo: "3 users",
        isSelected: false,
        folderId: "4",
    },
    {
        key: "17",
        name: "Budget Proposal.docx",
        size: "1.9 MB",
        lastModified: "Jun 29, 2023",
        sharedTo: "4 users",
        isSelected: false,
        folderId: "4",
    },
    {
        key: "18",
        name: "Client Feedback.xlsx",
        size: "6.7 MB",
        lastModified: "Jun 29, 2023",
        sharedTo: "7 users",
        isSelected: true,
        folderId: "4",
    },
    {
        key: "19",
        name: "Legal Agreement.docx",
        size: "2.5 MB",
        lastModified: "Jun 30, 2023",
        sharedTo: "5 users",
        isSelected: false,
        folderId: "5",
    },
    {
        key: "20",
        name: "Marketing Plan.pdf",
        size: "9.8 MB",
        lastModified: "Jun 30, 2023",
        sharedTo: "3 users",
        isSelected: true,
        folderId: "5",
    },
    {
        key: "21",
        name: "Product Launch Schedule.xlsx",
        size: "6.1 MB",
        lastModified: "Jul 1, 2023",
        sharedTo: "4 users",
        isSelected: false,
        folderId: "5",
    },
    {
        key: "22",
        name: "Project Timeline.pptx",
        size: "7.4 MB",
        lastModified: "Jul 1, 2023",
        sharedTo: "5 users",
        isSelected: true,
        folderId: "5",
    },
    {
        key: "23",
        name: "Vendor Agreement.pdf",
        size: "5.0 MB",
        lastModified: "Jul 2, 2023",
        sharedTo: "6 users",
        isSelected: false,
        folderId: "6",
    },
    {
        key: "24",
        name: "HR Policies.docx",
        size: "3.8 MB",
        lastModified: "Jul 2, 2023",
        sharedTo: "4 users",
        isSelected: true,
        folderId: "6",
    },
    {
        key: "25",
        name: "Company Budget.xlsx",
        size: "5.2 MB",
        lastModified: "Jul 3, 2023",
        sharedTo: "5 users",
        isSelected: false,
        folderId: "6",
    },
    {
        key: "26",
        name: "Quarterly Results.pptx",
        size: "7.1 MB",
        lastModified: "Jul 3, 2023",
        sharedTo: "3 users",
        isSelected: false,
        folderId: "6",
    },
    {
        key: "27",
        name: "Product Photos.zip",
        size: "4.0 MB",
        lastModified: "Jul 4, 2023",
        sharedTo: "6 users",
        isSelected: true,
        folderId: "7",
    },
    {
        key: "28",
        name: "Customer Survey Results.xlsx",
        size: "2.7 MB",
        lastModified: "Jul 4, 2023",
        sharedTo: "4 users",
        isSelected: false,
        folderId: "7",
    },
    {
        key: "29",
        name: "Competitor Analysis.pdf",
        size: "6.6 MB",
        lastModified: "Jul 5, 2023",
        sharedTo: "5 users",
        isSelected: true,
        folderId: "7",
    },
    {
        key: "30",
        name: "Investment Proposal.docx",
        size: "2.8 MB",
        lastModified: "Jul 5, 2023",
        sharedTo: "3 users",
        isSelected: false,
        folderId: "7",
    },
    {
        key: "31",
        name: "Performance Review.xlsx",
        size: "1.9 MB",
        lastModified: "Jul 6, 2023",
        sharedTo: "7 users",
        isSelected: false,
        folderId: "8",
    },
    {
        key: "32",
        name: "Business Strategy.pptx",
        size: "5.5 MB",
        lastModified: "Jul 6, 2023",
        sharedTo: "5 users",
        isSelected: false,
        folderId: "8",
    },
    {
        key: "33",
        name: "Meeting Agenda.docx",
        size: "4.0 MB",
        lastModified: "Jul 7, 2023",
        sharedTo: "3 users",
        isSelected: false,
        folderId: "8",
    },
    {
        key: "34",
        name: "Product Marketing.pdf",
        size: "6.8 MB",
        lastModified: "Jul 7, 2023",
        sharedTo: "4 users",
        isSelected: true,
        folderId: "8",
    },
    {
        key: "35",
        name: "Market Research.xlsx",
        size: "8.1 MB",
        lastModified: "Jul 8, 2023",
        sharedTo: "5 users",
        isSelected: false,
        folderId: "9",
    },
    {
        key: "36",
        name: "Team Performance Review.pptx",
        size: "4.5 MB",
        lastModified: "Jul 8, 2023",
        sharedTo: "6 users",
        isSelected: false,
        folderId: "9",
    },
    {
        key: "37",
        name: "Customer Journey Map.jpg",
        size: "3.3 MB",
        lastModified: "Jul 9, 2023",
        sharedTo: "4 users",
        isSelected: true,
        folderId: "9",
    },
    {
        key: "38",
        name: "Product Launch Plan.pdf",
        size: "6.4 MB",
        lastModified: "Jul 9, 2023",
        sharedTo: "5 users",
        isSelected: false,
        folderId: "9",
    },
    {
        key: "39",
        name: "Sales Presentation.pptx",
        size: "7.0 MB",
        lastModified: "Jul 10, 2023",
        sharedTo: "3 users",
        isSelected: false,
        folderId: "10",
    },
    {
        key: "40",
        name: "Training Manual.pdf",
        size: "2.9 MB",
        lastModified: "Jul 10, 2023",
        sharedTo: "5 users",
        isSelected: true,
        folderId: "10",
    },
];
